//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.name {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.name.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Ly Tu Trong, An Cu Ward, Ninh Kieu District, Can Tho City.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracelets are made from a variety of selected types of gold combined with quality stones and diamonds, and with the hands of many years of experience of jewelers, we create the best products to serve our customers the best. The most perfect item.
        /// </summary>
        internal static string BraceletsHome {
            get {
                return ResourceManager.GetString("BraceletsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color by the Yard Pendant.
        /// </summary>
        internal static string ColorbytheYardPendant {
            get {
                return ResourceManager.GetString("ColorbytheYardPendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2023 Jwelley: 1 Ly Tu Trong Street, An Cu Ward, Ninh Kieu Dictrict, Can Tho City, VietNam..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        internal static string Designer {
            get {
                return ResourceManager.GetString("Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNJ Diamond Platinum Wedding Ring.
        /// </summary>
        internal static string DiamondPlatinum {
            get {
                return ResourceManager.GetString("DiamondPlatinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jwelley@gmail.com.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Our Collections.
        /// </summary>
        internal static string ExCollections {
            get {
                return ResourceManager.GetString("ExCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featuring rare comno from the now closed Argyle Diamond, Stone, Gold most quality. These combo jewelry are truly unique and will become an heirloom for future generations or as an investment you can wear. Jewels of the Kimberley also have an amazing collection of loose Combo jewelry available for viewing by private appointment..
        /// </summary>
        internal static string FeaturingCombo {
            get {
                return ResourceManager.GetString("FeaturingCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featuring rare pink diamonds from the now closed Argyle Diamond Mine in Western Australia. These pink diamonds are truly unique and will become an heirloom for future generations or as an investment you can wear. Jewels of the Kimberley also have an amazing collection of loose pink diamonds available for viewing by private appointment..
        /// </summary>
        internal static string FeaturingHome {
            get {
                return ResourceManager.GetString("FeaturingHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduated Link Necklace.
        /// </summary>
        internal static string GraduatedLinkNecklace {
            get {
                return ResourceManager.GetString("GraduatedLinkNecklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Clients.
        /// </summary>
        internal static string HappyClients {
            get {
                return ResourceManager.GetString("HappyClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Diamonds Icons.
        /// </summary>
        internal static string HappyDiamondsIcons {
            get {
                return ResourceManager.GetString("HappyDiamondsIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Hearts.
        /// </summary>
        internal static string HappyHearts {
            get {
                return ResourceManager.GetString("HappyHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Spirit.
        /// </summary>
        internal static string HappySpirit {
            get {
                return ResourceManager.GetString("HappySpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Cube.
        /// </summary>
        internal static string IceCube {
            get {
                return ResourceManager.GetString("IceCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewels of the Yash Gems &amp; Jewelry.
        /// </summary>
        internal static string JewelsoftheYashGems_Jewelry {
            get {
                return ResourceManager.GetString("JewelsoftheYashGems&Jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juste Un Clou Single Earring.
        /// </summary>
        internal static string JusteUn {
            get {
                return ResourceManager.GetString("JusteUn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landspace at the store.
        /// </summary>
        internal static string Landspace {
            get {
                return ResourceManager.GetString("Landspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string LangVietnamese {
            get {
                return ResourceManager.GetString("LangVietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        internal static string Meeting {
            get {
                return ResourceManager.GetString("Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string menuHome {
            get {
                return ResourceManager.GetString("menuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New collections are released to our VIP customers, sign up to never miss out.
        /// </summary>
        internal static string NewCollections {
            get {
                return ResourceManager.GetString("NewCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our News.
        /// </summary>
        internal static string OurNews {
            get {
                return ResourceManager.GetString("OurNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Story.
        /// </summary>
        internal static string OurStory {
            get {
                return ResourceManager.GetString("OurStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        internal static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1234 567 890.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        internal static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive the latest product information, promotions and more..
        /// </summary>
        internal static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return and Warranty.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop By Product.
        /// </summary>
        internal static string ShopProduct {
            get {
                return ResourceManager.GetString("ShopProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to receive new news.
        /// </summary>
        internal static string SIGNUP {
            get {
                return ResourceManager.GetString("SIGNUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smile Pendant.
        /// </summary>
        internal static string SmilePendant {
            get {
                return ResourceManager.GetString("SmilePendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        internal static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNJ 14K White Gold Diamond Earrings.
        /// </summary>
        internal static string WhiteGold {
            get {
                return ResourceManager.GetString("WhiteGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YASH GEMS &amp; JEWELRY.
        /// </summary>
        internal static string YASHGEMS_JEWELRY {
            get {
                return ResourceManager.GetString("YASHGEMS&JEWELRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yash&apos;s ComBo Jewelry.
        /// </summary>
        internal static string Yash_SComBoJewelry {
            get {
                return ResourceManager.GetString("Yash\'SComBoJewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yash&apos;s Bracelet.
        /// </summary>
        internal static string Yash_s_Bracelet {
            get {
                return ResourceManager.GetString("Yash\'s Bracelet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18K PNJ Gold Earrings Jewels.
        /// </summary>
        internal static string _18KGold {
            get {
                return ResourceManager.GetString("18KGold", resourceCulture);
            }
        }
    }
}
